# Generated by Django 2.2.3 on 2019-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinterna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='html',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='js',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='python',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
