# Generated by Django 2.2.3 on 2019-07-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinterna', '0004_matriculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriculo',
            new_name='Matricula',
        ),
    ]
